language: python

python:
  - "3.4"

services: mysql

env:
  global:
    - DJANGO_SETTINGS_MODULE="djangotravis.settings"
    - PYTHONPATH="/home/travis/build/my_github_name/my_github_project"
    - PIP_USE_MIRRORS=true
  matrix:
    - DJANGO=1.7 DB=mysql

#commands to install dependencies
install:
  # - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt

before_script:
  - mysql -e 'create database travis_ci_db;'
  - python manage.py makemigrations
  - python manage.py migrate
  # - python manage.py syncdb --noinput

#command to run the test suite
script:
  - python manage.py test